[package]
name = "ascon-core"
description = "Pure rust implementation of the Ascon permutation"
version = "0.1.0"
authors = ["Sebastian Ramacher <sebastian.ramacher@ait.ac.at>"]
license = "MIT"
repository = "https://github.com/sebastinas/ascon-aead"
homepage = "https://github.com/sebastinas/ascon-aead"
readme = "README.md"
edition = "2021"
rust-version = "1.56"
keywords = ["Ascon"]
categories = ["cryptography", "no-std"]
exclude = [".github/", ".gitignore"]
